learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_logs.urls')),
    path('users/', include('users.urls')),
]

learning_logs/urls.py
from django.urls import path
from . import views

app_name = 'learning_logs'
urlpatterns = [
    path('', views.index, name='index'),
    path('topics/', views.topics, name='topics'),
    path('topic/<int:topic_id>/', views.topic, name='topic'),
    path('new_topic/', views.new_topic, name='new_topic'),
    path('edit_topic/<int:topic_id>/', views.edit_topic, name='edit_topic'),
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
]

users/urls.py
from django.urls import path, include
from . import views
app_name = 'users'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Entry(models.Model):
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        return f"{self.text[:50]}..."


class Comment(models.Model):
    date_added = models.DateTimeField(auto_now_add=True)
    text = models.TextField()
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    entry = models.ForeignKey(Entry, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.text[:50]}..."

users/models.py
from django.db import models


# Create your models here.

learning_logs/forms.py
from django import forms
from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['title', 'description']
        labels = {'description': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}

learning_logs/views.py
from django.shortcuts import render, redirect
from . models import Topic
from . forms import TopicForm, EntryForm
from django.contrib.auth.decorators import login_required
from django.http import Http404


def index(request):
    return render(request, 'learning_logs/index.html')

@login_required
def topics(request):
    topics = Topic.objects.all()
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)


def topic(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    context = {'topic': topic}
    return render(request, 'learning_logs/topic.html', context)


def new_topic(request):
    if request.method != 'POST':
        form = TopicForm()
    else:
        form = TopicForm(data = request.POST)
        if form.is_valid():
            topic = form.save(commit=False)
            topic.owner = request.user
            topic.save()
            return redirect('learning_logs:topics')

    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)


def edit_topic(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404
    if request.method != 'POST':
        form = TopicForm(instance=topic)
    else:
        form = TopicForm(instance=topic, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topics')
    context = {'form': form, 'topic': topic}
    return render(request, 'learning_logs/edit_topic.html', context)


def new_entry(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404
    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid:
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=topic_id)
    context = {'form': form, 'topic': topic}
    return render(request, 'learning_logs/new_entry.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login


def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('learning_logs: index')
    context = {'form': form}
    return render(request, 'users/register.html', context)

learning_logs/templates/learning_logs/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Учебный журнал</title>
    <a href="{% url 'learning_logs:index' %}">Учебный журнал</a>
    <a href="{% url 'learning_logs:topics' %}">Темы</a>
    {% if user.is_authenticated %}
        Привет, {{ user.username }}.
        <a href="{% url 'users:logout' %}">Выйти</a>
    {% else %}
        <a href="{% url 'users:login' %}">Войти</a>
        <a href="{% url 'users:register' %}">Регистрация</a>
    {% endif %}
</head>
{% block content %}{% endblock content %}
<body>
</body>
</html>

learning_logs/templates/learning_logs/edit_topic.html
{% extends 'learning_logs/base.html' %}
{% block content %}
  <p>Редактировать тему.</p>
  <form action="{% url 'learning_logs:edit_topic' topic.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Применить</button>
  </form>
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends 'learning_logs/base.html' %}
{% block content %}
    <p>Добро пожаловать на сайт учебного журнала. <br><br> Здесь вы сможете узнать много нового и интересного.<p>
{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends 'learning_logs/base.html' %}
{% block content %}
  <p>Введите запись</p>
  <form action="{% url 'learning_logs:new_entry' topic.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Сохранить</button>
  </form>
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends 'learning_logs/base.html' %}
{% block content %}
<p>Добавить новую тему</p>
<form action="{% url 'learning_logs:new_topic' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Создать тему</button>
</form>
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}
{% block content %}
    <p>{{ topic.title }}</p>
    <p>{{ topic.description }}</p><br>
    <p>
    <a href="{% url 'learning_logs:edit_topic' topic.id %}">Редактировать тему</a>
    </p>
    <p>Записи по теме:</p><br>
    <ul>
        {% for entry in topic.entry_set.all %}
            <li>{{ entry.text }}</li>
            <ul>
                <p>Комментарии:</p>
                {% for comment in entry.comment_set.all %}
                    <li>{{ comment.text }}</li>
                {% endfor %}<br>
            </ul>
        {% empty %}
            <li>Нет записей по данной теме.</li>
        {% endfor %}
    </ul>
<a href="{% url 'learning_logs:new_entry' topic.id %}">Добавить запись</a>
{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %}
{% block content %}
    <ul>
        {% for topic in topics %}
            <li><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic.title }}</a></li>
        {% endfor %}
    </ul>
<a href="{% url 'learning_logs:new_topic' %}">Добавить тему</a>
{% endblock content %}

users/templates/users/register.html
{% extends 'learning_logs/base.html' %}
{% block content %}
    <form action="{% url 'users:register' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Зарегистрироваться</button>
        <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" >
    </form>
{% endblock content %}